version: 2

sources:
  - name: pipedrive
    description: "Seeded Pipedrive extracts"
    database: "{{ target.database }}"          # or omit if you always use the same DB
    schema: "{{ target.schema }}"
    tables:
      - name: activity
        columns:
          - name: activity_id
            tests: [not_null]
          - name: deal_id
            tests: [not_null]
          - name: type
            tests: [not_null]

      - name: activity_types
        columns:
          - name: id
            tests: [not_null, unique]
          - name: type
            tests: [not_null]

      - name: deal_changes
        columns:
          - name: deal_id
            tests: [not_null]
          - name: changed_field_key
            tests: [not_null]
          - name: new_value
          - name: change_time
            tests: [not_null]

      - name: stages
        columns:
          - name: stage_id
            tests: [not_null, unique]
          - name: stage_name
            tests: [not_null]

      - name: fields
        columns:
          - name: id
            tests: [not_null, unique]
          - name: field_key
            tests: [not_null]
